import os
import pandas as pd


# ============================================================
# INDUSTRIA-X
# Throughput Analysis - Model 3
# ============================================================

# Get the project root directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Location of Model 3 production summary
PRODUCTION_FILE = os.path.join(
    BASE_DIR,
    "business_module",
    "outputs",
    "production_summary.csv"
)


def load_production_data():
    """Load the production summary generated by Model 3 analysis."""

    if not os.path.exists(PRODUCTION_FILE):
        print("ERROR: production_summary.csv was not found.")
        print(f"Expected location: {PRODUCTION_FILE}")
        return None

    try:
        df = pd.read_csv(PRODUCTION_FILE)
        return df

    except Exception as e:
        print("ERROR: Could not read production_summary.csv")
        print(f"Details: {e}")
        return None


def get_production_value(df, metric_name):
    """Get a production value from the summary file."""

    if df is None or df.empty:
        return None

    # Expected columns from the Model 3 analysis
    metric_column = None
    value_column = None

    for column in df.columns:
        if column.lower() == "metric":
            metric_column = column

        if column.lower() == "value":
            value_column = column

    if metric_column is None or value_column is None:
        print("ERROR: production_summary.csv does not contain")
        print("the expected 'Metric' and 'Value' columns.")
        return None

    result = df[
        df[metric_column].astype(str).str.strip().str.lower()
        == metric_name.lower()
    ]

    if result.empty:
        return None

    try:
        return float(result.iloc[0][value_column])
    except (ValueError, TypeError):
        return None


def calculate_throughput(df):
    """Calculate throughput-related metrics."""

    average = get_production_value(df, "Average")
    minimum = get_production_value(df, "Minimum")
    maximum = get_production_value(df, "Maximum")

    if average is None:
        # Try alternative names if the CSV uses different labels
        average = get_production_value(df, "Average Production")

    if minimum is None:
        minimum = get_production_value(df, "Minimum Production")

    if maximum is None:
        maximum = get_production_value(df, "Maximum Production")

    results = {
        "Average Production": average,
        "Minimum Production": minimum,
        "Maximum Production": maximum,
    }

    # Production range
    if minimum is not None and maximum is not None:
        results["Production Range"] = maximum - minimum
    else:
        results["Production Range"] = None

    # Difference between maximum and average
    if maximum is not None and average is not None:
        results["Maximum vs Average Difference"] = maximum - average
    else:
        results["Maximum vs Average Difference"] = None

    # Difference between average and minimum
    if average is not None and minimum is not None:
        results["Average vs Minimum Difference"] = average - minimum
    else:
        results["Average vs Minimum Difference"] = None

    return results


def print_report(results):
    """Print a readable throughput report."""

    print("\n" + "=" * 55)
    print("          INDUSTRIA-X THROUGHPUT ANALYSIS")
    print("=" * 55)

    print("\nMODEL 3 PRODUCTION")

    average = results["Average Production"]
    minimum = results["Minimum Production"]
    maximum = results["Maximum Production"]
    production_range = results["Production Range"]

    if average is not None:
        print(f"Average Production : {average:.2f}")
    else:
        print("Average Production : Not available")

    if minimum is not None:
        print(f"Minimum Production : {minimum:.2f}")
    else:
        print("Minimum Production : Not available")

    if maximum is not None:
        print(f"Maximum Production : {maximum:.2f}")
    else:
        print("Maximum Production : Not available")

    if production_range is not None:
        print(f"Production Range   : {production_range:.2f}")
    else:
        print("Production Range   : Not available")

    print("\nTHROUGHPUT OBSERVATIONS")

    if average is not None and minimum is not None and maximum is not None:

        if maximum > average:
            print(
                f"Maximum production is "
                f"{maximum - average:.2f} units above average."
            )

        if average > minimum:
            print(
                f"Average production is "
                f"{average - minimum:.2f} units above minimum."
            )

        if production_range is not None:
            print(
                f"Production varies across a range of "
                f"{production_range:.2f} units."
            )

    else:
        print("Insufficient production data for observations.")

    print("\nSOURCE")
    print("business_module/outputs/production_summary.csv")

    print("\n" + "=" * 55)
    print("              END THROUGHPUT ANALYSIS")
    print("=" * 55)


def main():
    """Main execution function."""

    print("\nLoading Model 3 production data...")

    df = load_production_data()

    if df is None:
        return

    print("Production summary loaded successfully.")

    results = calculate_throughput(df)

    print_report(results)


if __name__ == "__main__":
    main()